stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/load_data.py
    outs:
      - Training_Raw_Files

  validate_data:
    cmd: python src/validate_data.py --config=params.yaml
    deps:
      - src/validate_data.py
      - src/load_data.py

  transform_data:
    cmd: python src/transform_data.py --config=params.yaml
    deps:
      - src/transform_data.py
      - src/load_data.py

  insert_data:
    cmd: python src/insert_data_to_db.py --config=params.yaml
    deps:
      - src/insert_data_to_db.py
      - src/load_data.py
    outs:
      - Training_Database/Training.db
      - Consolidated_Training_Data/InputFile.csv

  train_model:
    cmd: python src/train_model.py --config=params.yaml
    deps:
      - Consolidated_Training_Data/InputFile.csv
      - src/train_model.py
      - src/load_data.py
    params:
      - estimators.KNNImputer.params.n_neighbors
      - estimators.KNNImputer.params.weights
      - estimators.XGBoost.params.learning_rate
      - estimators.XGBoost.params.max_depth
      - estimators.XGBoost.params.n_estimators
      - estimators.RandomForest.params.n_estimators
      - estimators.RandomForest.params.criterion
      - estimators.RandomForest.params.max_depth
      - estimators.RandomForest.params.max_features
      - estimators.GridSearchCV.params.verbose
      - estimators.GridSearchCV.params.cv

    metrics:
      - Reports/params.json:
          cache: false
      - Reports/scores.json:
          cache: false






