stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/load_data.py
      - Training_Batch_Files
    outs:
      - Training_Raw_Files

  validate_data:
    cmd: python src/validate_data.py --config=params.yaml
    deps:
      - src/validate_data.py
      - src/load_data.py
      - Training_Raw_Files
    outs:
      - Training_Raw_Files_Validated/Good_Raw
      - Training_Raw_Files_Validated/Bad_Raw

  transform_data:
    cmd: python src/transform_data.py --config=params.yaml
    deps:
      - src/transform_data.py
      - src/load_data.py
      - Training_Raw_Files_Validated/Good_Raw

  insert_data:
    cmd: python src/insert_data_to_db.py --config=params.yaml
    deps:
      - src/insert_data_to_db.py
      - src/load_data.py
    outs:
      - Training_Database/Training.db
      - Consolidated_Training_Data/InputFile.csv

