base:
  project: Machine Fault Recognition
  random_state: 10
  col_2_rmv: Wafer
  target_col: Output

s3_info:
  data_bucket: wafer-data
  train_folder: historical-data/
  pred_folder: current-data/
  models_bucket: wafer-models
  output_bucket: wafer-output
  reports_bucket: wafer-reports

load_data:
  raw_data: Training_Raw_Files

validate_data:
  train_schema: src/schema_training.json
  raw_validated: Training_Raw_Files_Validated
  good_raw: Training_Raw_Files_Validated/Good_Raw/
  bad_raw: Training_Raw_Files_Validated/Bad_Raw/
  raw_archived: Training_Archive_BadData/

prepare_data:
  train_db_folder: Training_Database/
  train_folder: Consolidated_Training_Data/
  train_file: Consolidated_Training_Data/InputFile.csv
    
reports:
  main: Reports/
  null_values_train: Reports/null_values_train_data.csv
  null_values_prediction: Reports/null_values_prediction_data.csv
  Kmeans_elbow_plot: Reports/K-Means_Elbow.PNG
  params: Reports/params.json
  scores: Reports/scores.json
  cols2rmv: Reports/redundant_columns.txt

estimators:
  KNNImputer:
    params:
      n_neighbors: 3
      weights: uniform
  XGBoost:
    params:
      learning_rate: [0.5, 0.1, 0.01, 0.001]
      max_depth: [3, 5, 10, 20]
      n_estimators: [10, 50, 100, 200]
  RandomForest:
    params:
      n_estimators: [10, 50, 100, 130]
      criterion: ['gini', 'entropy']
      max_depth: [2, 3, 4]
      max_features: ['auto', 'log2']
  GridSearchCV:
    params:
      verbose: 2
      cv: 5

models: models/

split_data:
  test_size: 0.33

predict_data:
  prediction_schema: src/schema_prediction.json
  raw_validated: Prediction_Raw_Files_Validated
  good_raw: Prediction_Raw_Files_Validated/Good_Raw/
  bad_raw: Prediction_Raw_Files_Validated/Bad_Raw/
  raw_archived: Prediction_Archive_BadData/
  prediction_db_folder: Prediction_Database/
  prediction_folder: Consolidated_Prediction_Data/
  prediction_file: Consolidated_Prediction_Data/InputFile.csv
  prediction_final_file: Prediction_Output_File/Predictions.csv



